version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: StockWebsite
    container_name: flask_sdvc
    ports:
      - "5005:5000"
    volumes:
       - .:/app
    environment:
      FLASK_DEBUG: "1" 